import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
 import 'react-toastify/dist/ReactToastify.css';
import TanstackProvider from "@/components/common/tanstackQuery/TanstackProvider";
import { AuthProvider } from "@/components/common/Providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <TanstackProvider>
                        {children}
                    </TanstackProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
