export  const EMAIL_REQUIRED = "Email is required" 
export const PASSWORD_REQUIRED = "Password is required"
export const PLEASE_ENTER_VALID_FORMAT = "Please enter a valid email format"
export const VALUE_REQUIRED = "Value is required"
export const PASSWORD_MIN_LENGTH_MESSAGE = "Please enter at least 8 alphanumeric characters"
export const WRONG_PASSWORD = "The password is incorrect, please check again";
export const WRONG_EMAIL = "Email is incorrect or does not exist";
export const PHONE_NUMBER_REQUIRED_MESSAGE = "Phone number is required"
export const PHONE_NUMBER_WRONG_MESSAGE = 'The phone number must be in the correct format';